### ISSUE TITLE
question to function "lightsleep"

### ISSUE THREAD

**Issue by Sen5ation** [felmue/MyM5StackExamples#1]
Hi,

in file https://github.com/felmue/MyM5StackExamples/blob/main/M5Paper/Lightsleep.py  you put the script in line 19 in lightsleep. so far so trivial.
But, i saw online, that there is a way to get the device wake up by touch input.
Source: https://docs.m5stack.com/zh_CN/mpy/official/machine
```
esp32.wake_on_touch(True)
machine.lightsleep() # put the MCU to sleep until a touchpad is touched
```
Do you know how though? I'm not able to get it working.

To give you some context, this is my main function:
```
esp32.wake_on_touch(True)

#one_sec = 1000
while True:
    power.ext_power_on() # turn Groove port power on
    wait(1)
    power.ext_power_off() # turn Groove port power off

    from machine import Pin, lightsleep
    Pin(2, Pin.OUT, value=1, pull=Pin.PULL_HOLD) # M5EPD_MAIN_PWR_PIN

    showSymbol("S")
    lightsleep(1000*60)
    showSymbol("A")

    wait_ms(2)
    if touch.status():
        varTouchList = touch.read()
        varTouchx = varTouchList[0]
        varTouchY = varTouchList[1]
        # do some touch input actions
```
So as you see I want to wake up from a touch input, check if there is a touch input, do something accordingly and than return to sleep.
Is there a smart way to do that?

**Comment by felmue** [comment]
Hello @Sen5ation 

I assume your intention is to wake M5Paper when its touch screen is touched, correct?

The line of code `esp32.wake_on_touch(True)` refers to GPIOs which can be used as touchpads. From the description: _There are ten capacitive touch-enabled pins that can be used on the ESP32: 0, 2, 4, 12, 13 14, 15, 27, 32, 33. Trying to assign to any other pins will result in a ValueError_. Touchpads are something different from the M5Paper touch screen.

When the M5Paper touch screen is touched its INT line goes LOW, which, according to the diagram in the back of M5Paper, is connected to GPIO36 of the ESP32. You'll need to look into how ESP32 can be woken up from light sleep when GPIO36 goes LOW.

Thanks
Felix

**Comment by Sen5ation** [comment]
Thans for that advice! I did not know that touchpad and touchscreens are two separate thinks here.

My working code looks like this:
```
push_button = machine.Pin(36, mode = Pin.IN)     #setting push_button as wake up source
lcd.show()

esp32.wake_on_ext0(pin = push_button, level = esp32.WAKEUP_ALL_LOW)  #initializing wake up
```

**Comment by felmue** [comment]
@Sen5ation 

cool. I am glad you got it working to your liking. And thank you for reporting back and posting your solution.

Thanks
Felix
