### ISSUE TITLE
M5stack core basic, SIM7600G, OTA, invalid segment length

### ISSUE THREAD

**Issue by Dan-Kiefer** [felmue/MyM5StackExamples#2]
Hi felmue
I used your code 'OTAoverLTE.ino', which seems to work seamlessly until the end. But then there is an error message about an 'invalid segment length'.
Here is the response I get:
Modem Info: ATI  Manufacturer: SIMCOM INCORPORATED Model: SIMCOM_SIM7600G-H Revision: SIM7600M22_V2.0.1 SVN: 01 IMEI: 8xxxxxxxxxx2 +GCAP: +CGSM
Waiting for network... success
Network connected
Connecting to internet success
GPRS connected
Connecting to xxxxxxx.ch success
Waiting for response header

HTTP/1.1 200 OK- - Date: Wed, 24 May 2023 12:23:36 GMT- - Server: Apache- - Upgrade: h2,h2c- - Connection: Upgrade, close- - Last-Modified: Wed, 24 May 2023 11:11:02 GMT- - ETag: "5xxxxxxxxxxxxxx5"- - Accept-Ranges: bytes- - Content-Length: 388720- - Content-Type: application/octet-stream- - - - Content-length: 388720

Update begin ok
Reading response data

 0.00%
 7.69%
 15.38%
 23.08%
 30.77%
 38.46%
 46.15%
 53.85%
 61.54%
 69.23%
 76.92%
 84.61%
 92.31%[73261] ### Closed:  0

 100.00%
 100.00%
E (74036) esp_image: invalid segment length 0xffffffff
Error Occurred. Error #: 9
Server disconnected
GPRS disconnected

Content-Length: 388720
Actually read:  388720
Duration:       54.70s

Do you have any clue what I may be doing wrong?
Thanks and kind regards, Dan

**Comment by felmue** [comment]
Hello @Dan-Kiefer 

have you tried multiple times? And if yes, does it always fail after the same amount of downloaded data?
Here are some ideas:
- have you tried a different server?
- have you tried a different power source?
- have you tried a different position for the modem?
- have you tried a different (size) firmware file?

Note: the modem I have is a SIM7600G (without the H) which I think means lower speed. Shouldn't make a difference though.

Thanks
Felix

**Comment by Dan-Kiefer** [comment]
Hi felmue

thanks for your prompt reply!

Yes, I tried many, many times, with always the same result. Playing with different delays and timeouts didn't help.

Yes, I have tried different positions of the modem.

No, I have not yet tried with a different power source. So far the symptoms do not make me suspect the hardware. 92.31% is always the end, regardless of the length of the file and the duration of the transfer. This does not look like a power supply problem. Do you agree?

As the numbers 'Content-Length:' and 'Actually read:' were the same, I didn't question whether the data actually arrived on the M5. The file size corresponds exactly to the file size shown by windows explorer. Therefore I thought, the file was received correctly. It's only now that I realize that the 'closing' always takes place after 92.31%. No idea what the 100% in the serial monitor means though. Do you know more about this?

Even with the smallest program possible (draw 'Hello' on the screen), the closing takes place after 92.31%.

The same thing happens with a program three times the size. The duration also triples, but the 'closing' still happens after 92.31%.

 0.00%
 7.69%
 15.38%
 23.08%
 30.77%
 38.46%
 46.15%
 53.85%
 61.54%
 69.23%
 76.92%
 84.61%
 92.31%[176859] ### Closed:  0

 100.00%
 100.00%
E (177551) esp_image: invalid segment length 0xffffffff
Error Occurred. Error #: 9
Server disconnected
GPRS disconnected

Content-Length: 1122640
Actually read:  1122640
Duration:       157.81s


I played around with the size of 'TINY_GSM_RX_BUFFER', which didn't help, but slightly changed duration of the process.

So far I did not question the server (hostpoint), because the OTA worked fine when I used the ESP32's WiFi functionality. The problem is only with the SIM7600G module. Also I don't have another server available. This evening I will try to access xampp on my laptop from outside. Not yet sure how to achieve that.
Or do you know of a public http server with test binaries for ESP32 that I could test this with?

Thanks again, Dan

**Comment by Dan-Kiefer** [comment]
In my last post I asked for a public http server with a binary for testing. There is actually an [example](https://github.com/espressif/esp-idf/issues/4080#issuecomment-538271762 ) for https. But as TinyGSM is not yet ready for https for the SIM7600 module, I have to work with http.
Regards, Dan

**Comment by felmue** [comment]
Hello @Dan-Kiefer 

I don't know if the error means incorrect / not complete download or if it means something is going wrong later on when checking the downloaded file.

Since my code is based on the file download example from [here](https://github.com/vshymanskyy/TinyGSM/blob/master/examples/FileDownload/FileDownload.ino); maybe you could try to see if that works any better?

Thanks
Felix

**Comment by Dan-Kiefer** [comment]
Hello Felix
just double checked it with the file you linked. It provides the same result. 
Now I printed to the serial monitor all characters received. I can clearly see all Bytes of the file transmitted. 8 of them actually arrive after the '100% 100%' written by the 'Update.h'. There are 8 additional bytes at the start of the transmitted data, in front opf the data of the actual file. I guess that must be some kind of header. I will now try to somehow drop these first Bytes and see what happens.
Regards, Dan

**Comment by felmue** [comment]
Hello @Dan-Kiefer 

Firstly: just noticed - you might want to redact your IMEI in your first post.

I've rerun the example here a couple of times and it worked every time. I think in your case the actual download works fine as it reaches 100%. But yes, the actual data might be incorrect so I am curious about what you find.

In the mean time I am wondering if something goes wrong writing the data to the flash, so

- have you tried to fully erase the flash?
- have you tried with a different ESP32?

Thanks
Felix

**Comment by Dan-Kiefer** [comment]
Hello Felix

Yes I tried with another ESP32. Same result. Fully erase flash doesn't help either.

But: Yesterday I was confused about the '100%' message on the serial monitor, which was displayed before the last 8 bytes arrived. This is actually due to the fact that the 'printPercent' routine is called in an if-clause with a modulo operator in its condition. If the number of bytes is not a multiple of 13, the 100% are displayed too early. In my case it was 8 bytes before the end of the data. Which is not a problem, it just lead me to wrong conclusions.

That still doesn't solve my problem, but at least I now know, that the data arrives perfectly well on my ESP. I compared the data received with a hex editor, they are all perfect. It's just the update that goes wrong.

Regards, Dan

**Comment by Dan-Kiefer** [comment]
Thank you for the hint regarding IMEI.

**Comment by Dan-Kiefer** [comment]
As you see, I am new to this forum. Do you think it might be useful to ask the question concerning the 'esp_image: invalid segment length 0xffffffff' to the creater of 'Update.h'. Or will that be considered a 'double posting'?
Thanks for your advice!

**Comment by felmue** [comment]
Hello @Dan-Kiefer 

I think that would be ok. My experience is that asking doesn't cost much and being polite, like you are, helps as well.

Thanks
Felix

**Comment by Dan-Kiefer** [comment]
Hello Felix,
thanks for your help. I just posted the question [here](https://github.com/espressif/arduino-esp32/issues/8267). ('awaiting triage', so you may not yet be able to see it.)
Kind regards, Dan

**Comment by Dan-Kiefer** [comment]
Hello Felix
I was finally able to solve the problem, which was due to a strangely modified library 'Update.h' on my PC. No idea how it got there.
It works fine now, based on your code! Thanks a lot!
Kind regards, Dan

**Comment by felmue** [comment]
Hello @Dan-Kiefer 

I am glad to hear you (finally) got it working. And thank you for reporting back to me.

Thanks
Felix
