### ISSUE TITLE
Core2 SimpleTone.py

### ISSUE THREAD

**Issue by lidonglei1** [felmue/MyM5StackExamples#4]
May I know which version of mpy firmware you used to run MyM5StackExamples/M5Core2/SimpleTone.py? 
I used M5core2v1.12.5, but it prompted "I2S.MONO not found".  
Thank you

**Comment by felmue** [comment]
Hello @lidonglei1 

thank you for your report. This example uses LVGL Micropython firmware (not UIFlow).

https://github.com/lvgl/lv_micropython/tree/master/ports/esp32/boards/M5CORE2

I've added some comment to the example to clarify that fact.

Thanks
Felix

**Comment by lidonglei1** [comment]
> Hello @lidonglei1 
> 
> thank you for your report. This example uses LVGL Micropython firmware (not UIFlow).
> 
> https://github.com/lvgl/lv_micropython/tree/master/ports/esp32/boards/M5CORE2
> 
> I've added some comment to the example to clarify that fact.
> 
> Thanks
> Felix
> 

OK I see.
Thank you very much

**Comment by lidonglei1** [comment]
> Hello @lidonglei1
> 
> thank you for your report. This example uses LVGL Micropython firmware (not UIFlow).
> 
> https://github.com/lvgl/lv_micropython/tree/master/ports/esp32/boards/M5CORE2
> 
> I've added some comment to the example to clarify that fact.
> 
> Thanks Felix

Hi felmue 
I run lv_micropython on core2,and run SimpleTone.py,
but "Traceback (most recent call last):
  File "<stdin>", line 59, in <module>
NameError: name 'power' isn't defined"
where can I find the power.py?
Thank you

**Comment by felmue** [comment]
Hello @lidonglei1 

Hmm, I do not get this error. That said [power.py](https://github.com/lvgl/lv_micropython/blob/master/ports/esp32/boards/M5CORE2/modules/power.py) is a module for M5Core2 and I think it should be included automatically.

Thanks
Felix

**Comment by lidonglei1** [comment]
> Hello @lidonglei1
> 
> Hmm, I do not get this error. That said [power.py](https://github.com/lvgl/lv_micropython/blob/master/ports/esp32/boards/M5CORE2/modules/power.py) is a module for M5Core2 and I think it should be included automatically.
> 
> Thanks Felix
Hi felmue
There might be an issue with the firmware I compiled for Core2. 
Could you send me your firmware instead?
my email：lidonglei1@163.com
Thanks

**Comment by felmue** [comment]
Hello @lidonglei1 

please try to add the following two lines at the top of the file.

from power import Power
power = Power()

Thanks
Felix

**Comment by lidonglei1** [comment]
> Hello @lidonglei1
> 
> please try to add the following two lines at the top of the file.
> 
> from power import Power power = Power()
> 
> Thanks Felix

It works！
Thank you very much
